version: '3'

services:
  database:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=web01
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - /home/web01/database/db/:/var/lib/mysql
    networks:
      - temp_network
  
  application:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on:
      - database
    container_name: app01
    networks:
      - temp_network

networks:
  temp_network: